leftnav:
- identifier: 070f871c-7690-7ba5-f845-e838001eeb96
  name: Syllabus
  url: /pages/syllabus/
  weight: 10
- identifier: 0aaef1d5-a0ec-1f6d-0adb-7edf3fdb855c
  name: Course Objectives and Outcomes
  parent: 070f871c-7690-7ba5-f845-e838001eeb96
  url: /pages/syllabus/course-objectives-and-outcomes
  weight: 20
- identifier: c1d98983-233b-dd0f-c54c-280cee6469cb
  name: Collaboration Policy
  parent: 070f871c-7690-7ba5-f845-e838001eeb96
  url: /pages/syllabus/collaboration-policy
  weight: 30
- identifier: 65b6536a-9894-b29b-38b5-533efd54aed6
  name: Calendar
  url: /pages/calendar
  weight: 40
- identifier: d6436bd3-f1dc-d6ed-db45-46ff67a8d147
  name: Readings
  url: /pages/readings
  weight: 50
- identifier: 54da7b67-8d41-8434-419d-7dd9ed78d45f
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 60
- identifier: 5f78770b-ebc1-f8f6-1ef0-07b624b9e167
  name: Recitations
  url: /pages/recitations
  weight: 70
- identifier: bda74b8b-6fee-ffd8-7de9-5efad51ec4e2
  name: Assignments
  url: /pages/assignments
  weight: 80
- identifier: ac9c0175-3f4c-9395-6b2d-83ab62ef3e13
  name: Exams
  url: /pages/exams
  weight: 90
